// LIYU SUN_CMPM 120
// CHUNGKING EXPRESS
// 30-40 HOURS
/* 
   CITATIONS:
        Music generated by Mubert https://mubert.com/render

        Play Music          : https://github.com/photonstorm/phaser3-examples/blob/master/public/src/audio/Web%20Audio/play%20audio%20file.js
        Menu&End Bitmap     : https://github.com/nathanaltice/Paddle-Parkour-P360
        FSM                 : https://github.com/nathanaltice/FSM
        "Piacevoli" Font    : https://fontenddev.com/fonts/piacevoli/
        Loading Bar         : https://rexrainbow.github.io/phaser3-rex-notes/docs/site/loader/

    
    Creative Tilt Justification:
        - 
        - 

*/

'use strict';

let config =
{
    type    : Phaser.AUTO,
    width   : 800,
    height  : 600,
    scale: 
    {
        autoCenter: Phaser.Scale.CENTER_BOTH
    },
    physics: 
    {
        default: 'arcade',
        arcade: 
        {
            debug: false,
            gravity: 
            {
                x: 0,
                y: 0
            }
        }
    },
    scene   : [ Menu, Achievement, Credits, CutOne, CutTwo, CutThree, CutFour, CutFive, PlayOne, PlayTwo, PlayThree, Over ] 
}

let game = new Phaser.Game(config);

// def globals for positioning
let centerX         = game.config.width/2;
let centerY         = game.config.height/2;
let wdth            = game.config.width;
let hght            = game.config.height;
const textSpacer    = 64;
const paddingSize   = 100;


// def globals for functional var
let purchaseCmplt   = false;
let purchaseDate    = 1;
let saladCount      = 0;
let firstTimer      = 15000;

let typeTimeOut     = false;
let firstAnsFin     = false;
let secondAnsFin    = false;
let thirdAnsFin     = false;
let firstAns        = false;
let secondAns       = false;
let thirdAns        = false;

let findFirst       = false;
let findSecond      = false;
let findThird       = false;

let timerEnd        = false;

// reserve keyboard variables
let keyW, keyA, keyS, keyD, keyY, keyU, keyI, keyO, keyP, keyF;

let cursors = null;